_target_: forecast_mae_prediction.src.datamodule.lmdb_datamodule.LmdbDataModule

data_root: ${data_root}
data_folder: ${model.name}
train_batch_size: ${batch_size}
val_batch_size: ${batch_size}
test_batch_size: ${batch_size}
shuffle: True
num_workers: ${num_workers}
pin_memory: True
