name: forecast-mae
phase: tail_prediction

target:
  _target_: forecast_mae_prediction.src.model.trainer_tail_prediction.Trainer
  dim: 128
  historical_steps: 10
  future_steps: 30
  encoder_depth: 4
  decoder_depth: 4
  num_heads: 8
  mlp_ratio: 4.0
  qkv_bias: False
  drop_path: 0.2
  actor_mask_ratio: 0.5
  lane_mask_ratio: 0.5
  loss_weight: [1.0, 1.0, 0.35]
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
